# Generated by Django 4.2.7 on 2023-11-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0002_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciepe',
            name='reciepe_image',
            field=models.ImageField(blank=True, null=True, upload_to='reciepe'),
        ),
    ]
